apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ratings
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/ratings/
        pathType: Prefix
        backend:
          service:
            name: ratings
            port:
              name: http